language: go

addons:
  apt:
    packages:
      - libappindicator3-dev
      - libgtk-3-dev

install: true

env:
  - GO111MODULE=on

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
  - go generate

script:
  - golangci-lint run
  - go test -v -race ./...
  - go run build.go
